version: '3.7'

services:
  web:
    build: .
    command: >
      gunicorn -b 0.0.0.0:8000
        --access-logfile -
        --reload
        "snakeeyes.app:create_app()"
    volumes:
      - '.:/snakeeyes'
    ports:
      - '8000:8000'
